export { default as HeroSection } from "./HeroSection";
export { default as StatsSection } from "./StatsSection";
export { default as FeaturesSection } from "./FeaturesSection";
export { default as PopularComparisonsSection } from "./PopularComparisonsSection";
export { default as ExploreCoursesSection } from "./ExploreCoursesSection";
export { default as HowItWorksSection } from "./HowItWorksSection";
export { default as RankingsPreviewSection } from "./RankingsPreviewSection";
export { default as TestimonialsSection } from "./TestimonialsSection";
export { default as CtaSection } from "./CtaSection";
